[package]
name = "token-program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "2.0.5"
solana-sdk = "2.0.5"
solana-program = "2.0.5"
spl-token = "6.0.0"
spl-associated-token-account = "4.0.0"
arrayref = "0.3.6"
